my:
  greeting: Updated "Hello World" From My GitHub Repository
  list:
    values: One,Two,Three, Four, Five, Six
db:
  connection: connection-string-here-from-updated-config-repo-on-github
  host: 129.0.0.1
  port: 2400
